# Generated by Django 4.1.7 on 2023-03-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='avatar/%Y%m%d')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['text']},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
        migrations.AddField(
            model_name='article',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='article.avatar'),
        ),
        migrations.AddField(
            model_name='category',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='article.avatar'),
        ),
    ]
