# Generated by Django 4.1.7 on 2023-03-12 07:44

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_avatar_alter_tag_options_rename_tag_tag_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='content',
            field=models.ImageField(upload_to=article.models.user_directory_path),
        ),
    ]
