# Generated by Django 4.1.7 on 2023-03-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='BookTag',
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
