# Generated by Django 4.1.7 on 2023-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_rename_tag_booktag_course_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='requisites',
        ),
        migrations.AlterField(
            model_name='course',
            name='offered',
            field=models.TextField(),
        ),
    ]
