# Generated by Django 4.1.7 on 2023-03-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_remove_course_requisites_alter_course_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='offered',
        ),
    ]
