# Generated by Django 4.1.7 on 2023-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0004_remove_course_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offered',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requisites',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
